services:
  postgres:
    image: postgres:17
    container_name: ocserv-postgres
    restart: always
#    environment: # not needed, read from .env file
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - /opt/ocserv_dashboard/docker_volumes/pg_db:/var/lib/postgresql/data
    networks:
      - shared-app
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:5435:5432" # develop expose port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ocserv:
    build:
      context: .
      dockerfile: Dockerfile-Ocserv
    image: ocserv_users_management:ocserv_with_api
    container_name: ocserv
    privileged: true
    env_file:
      - ./.env
    environment:
      ALLOW_ORIGINS: "${ALLOW_ORIGINS}"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/ocserv_dashboard/docker_volumes/db:/usr/local/bin/db  # deprecated (sqlite)
      - /opt/ocserv_dashboard/docker_volumes/ocserv:/etc/ocserv
    ports:
      - ${OCSERV_PORT:-443}:443/tcp
      - ${OCSERV_PORT:-443}:443/udp
    networks:
      - shared-app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  log_stream:
    image: ocserv_users_management:log_stream
    build:
      context: .
      dockerfile: Dockerfile-Stream-Log
    container_name: log_stream
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    networks:
      - shared-app
    depends_on:
      ocserv:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  user_expiry:
    image: ocserv_users_management:user_expiry
    build:
      context: .
      dockerfile: Dockerfile-User-Expiry
    container_name: user_expiry
    volumes:
      - /opt/ocserv_dashboard/docker_volumes/cron_journal:/app/cron_journal # journal of user expiry .txt file
    env_file:
      - ./.env
    networks:
      - shared-app
    depends_on:
      ocserv:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  web:
    image: ocserv_users_management:web
    build:
      context: .
      dockerfile: Dockerfile-Web
      args:
        - LANGUAGES=${LANGUAGES}
    container_name: web
    volumes:
      - /opt/ocserv_dashboard/docker_volumes/nginx/certs:/etc/nginx/certs
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "3443:3443"
    networks:
      - shared-app
    depends_on:
      ocserv:
        condition: service_healthy
    restart: unless-stopped

networks:
  shared-app:
