# ================================
# Vue.js build stage
# ================================
FROM node:20 AS vue

# Build-time arguments
ARG API_URL
ARG LOG_SOCKET_URL
ARG LANGUAGES

WORKDIR /app

# Copy package.json first to leverage Docker cache
COPY web/package*.json web/yarn.lock ./

RUN yarn install

# Copy all source files
COPY ./web .

# Build Vue app with environment variables
RUN NODE_ENV=production \
    VITE_I18N_LANGUAGES="${LANGUAGES}" \
    yarn run build

# ================================
# Nginx production stage
# ================================
FROM nginx:alpine

# Install bash, gettext (for envsubst), and openssl
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache bash gettext openssl \
    && rm -rf /etc/nginx/conf.d/default.conf /usr/share/nginx/html \
    && mkdir -p /var/www/site /etc/nginx/certs


# Copy custom Nginx startup script
COPY scripts/nginx_docker.conf  /etc/nginx/conf.d/site.conf

COPY scripts/nginx_entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

COPY --from=vue /app/dist /var/www/site

VOLUME ["/etc/nginx/certs"]

EXPOSE 80 443

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
