/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction
} from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CustomerSummaryData } from '../models';
// @ts-ignore
import type { CustomerSummaryResponse } from '../models';
// @ts-ignore
import type { MiddlewaresTooManyRequests } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * CustomersApi - axios parameter creator
 * @export
 */
export const CustomersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSummaryPost: async (
            request: CustomerSummaryData,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('customersSummaryPost', 'request', request);
            const localVarPath = `/customers/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        }
    };
};

/**
 * CustomersApi - functional programming interface
 * @export
 */
export const CustomersApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomersApiAxiosParamCreator(configuration);
    return {
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomerSummaryData} request customer username and password (same ocserv account).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async customersSummaryPost(
            request: CustomerSummaryData,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.customersSummaryPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['CustomersApi.customersSummaryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        }
    };
};

/**
 * CustomersApi - factory interface
 * @export
 */
export const CustomersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomersApiFp(configuration);
    return {
        /**
         * Customer summary account
         * @summary Customer summary account
         * @param {CustomersApiCustomersSummaryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        customersSummaryPost(
            requestParameters: CustomersApiCustomersSummaryPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<CustomerSummaryResponse> {
            return localVarFp
                .customersSummaryPost(requestParameters.request, options)
                .then((request) => request(axios, basePath));
        }
    };
};

/**
 * Request parameters for customersSummaryPost operation in CustomersApi.
 * @export
 * @interface CustomersApiCustomersSummaryPostRequest
 */
export interface CustomersApiCustomersSummaryPostRequest {
    /**
     * customer username and password (same ocserv account).
     * @type {CustomerSummaryData}
     * @memberof CustomersApiCustomersSummaryPost
     */
    readonly request: CustomerSummaryData;
}

/**
 * CustomersApi - object-oriented interface
 * @export
 * @class CustomersApi
 * @extends {BaseAPI}
 */
export class CustomersApi extends BaseAPI {
    /**
     * Customer summary account
     * @summary Customer summary account
     * @param {CustomersApiCustomersSummaryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApi
     */
    public customersSummaryPost(
        requestParameters: CustomersApiCustomersSummaryPostRequest,
        options?: RawAxiosRequestConfig
    ) {
        return CustomersApiFp(this.configuration)
            .customersSummaryPost(requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }
}
