/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction
} from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { ModelsOcservUser } from '../models';
// @ts-ignore
import type { OcservUserSyncOcpasswdRequest } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * OcservOcpasswdSyncApi - axios parameter creator
 * @export
 */
export const OcservOcpasswdSyncApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {string} authorization Bearer TOKEN
         * @param {OcservUserSyncOcpasswdRequest} request list of users with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdSyncPost: async (
            authorization: string,
            request: OcservUserSyncOcpasswdRequest,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservUsersOcpasswdSyncPost', 'authorization', authorization);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservUsersOcpasswdSyncPost', 'request', request);
            const localVarPath = `/ocserv/users/ocpasswd/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        }
    };
};

/**
 * OcservOcpasswdSyncApi - functional programming interface
 * @export
 */
export const OcservOcpasswdSyncApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = OcservOcpasswdSyncApiAxiosParamCreator(configuration);
    return {
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {string} authorization Bearer TOKEN
         * @param {OcservUserSyncOcpasswdRequest} request list of users with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservUsersOcpasswdSyncPost(
            authorization: string,
            request: OcservUserSyncOcpasswdRequest,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsOcservUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservUsersOcpasswdSyncPost(
                authorization,
                request,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['OcservOcpasswdSyncApi.ocservUsersOcpasswdSyncPost']?.[localVarOperationServerIndex]
                    ?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        }
    };
};

/**
 * OcservOcpasswdSyncApi - factory interface
 * @export
 */
export const OcservOcpasswdSyncApiFactory = function (
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance
) {
    const localVarFp = OcservOcpasswdSyncApiFp(configuration);
    return {
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdSyncPost(
            requestParameters: OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<Array<ModelsOcservUser>> {
            return localVarFp
                .ocservUsersOcpasswdSyncPost(requestParameters.authorization, requestParameters.request, options)
                .then((request) => request(axios, basePath));
        }
    };
};

/**
 * Request parameters for ocservUsersOcpasswdSyncPost operation in OcservOcpasswdSyncApi.
 * @export
 * @interface OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest
 */
export interface OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPost
     */
    readonly authorization: string;

    /**
     * list of users with config to sync in db
     * @type {OcservUserSyncOcpasswdRequest}
     * @memberof OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPost
     */
    readonly request: OcservUserSyncOcpasswdRequest;
}

/**
 * OcservOcpasswdSyncApi - object-oriented interface
 * @export
 * @class OcservOcpasswdSyncApi
 * @extends {BaseAPI}
 */
export class OcservOcpasswdSyncApi extends BaseAPI {
    /**
     * Ocserv Users from ocpasswd file to db
     * @summary Ocserv Users from ocpasswd file to db
     * @param {OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservOcpasswdSyncApi
     */
    public ocservUsersOcpasswdSyncPost(
        requestParameters: OcservOcpasswdSyncApiOcservUsersOcpasswdSyncPostRequest,
        options?: RawAxiosRequestConfig
    ) {
        return OcservOcpasswdSyncApiFp(this.configuration)
            .ocservUsersOcpasswdSyncPost(requestParameters.authorization, requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }
}
