/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
    DUMMY_BASE_URL,
    assertParamExists,
    setApiKeyToObject,
    setBasicAuthToObject,
    setBearerAuthToObject,
    setOAuthToObject,
    setSearchParams,
    serializeDataIfNeeded,
    toPathString,
    createRequestFunction
} from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { OcservUserOcservUsersSyncResponse } from '../models';
// @ts-ignore
import type { OcservUserSyncOcpasswdRequest } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * OcservOcpasswdApi - axios parameter creator
 * @export
 */
export const OcservOcpasswdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv Users from ocpasswd file
         * @summary Ocserv Users from ocpasswd file
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {OcservUsersOcpasswdGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdGet: async (
            authorization: string,
            page?: number,
            size?: number,
            order?: string,
            sort?: OcservUsersOcpasswdGetSortEnum,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservUsersOcpasswdGet', 'authorization', authorization);
            const localVarPath = `/ocserv/users/ocpasswd`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        },
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {string} authorization Bearer TOKEN
         * @param {OcservUserSyncOcpasswdRequest} request list of users with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdSyncPost: async (
            authorization: string,
            request: OcservUserSyncOcpasswdRequest,
            options: RawAxiosRequestConfig = {}
        ): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservUsersOcpasswdSyncPost', 'authorization', authorization);
            // verify required parameter 'request' is not null or undefined
            assertParamExists('ocservUsersOcpasswdSyncPost', 'request', request);
            const localVarPath = `/ocserv/users/ocpasswd/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {
                ...localVarHeaderParameter,
                ...headersFromBaseOptions,
                ...options.headers
            };
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions
            };
        }
    };
};

/**
 * OcservOcpasswdApi - functional programming interface
 * @export
 */
export const OcservOcpasswdApiFp = function (configuration?: Configuration) {
    const localVarAxiosParamCreator = OcservOcpasswdApiAxiosParamCreator(configuration);
    return {
        /**
         * Ocserv Users from ocpasswd file
         * @summary Ocserv Users from ocpasswd file
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {OcservUsersOcpasswdGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservUsersOcpasswdGet(
            authorization: string,
            page?: number,
            size?: number,
            order?: string,
            sort?: OcservUsersOcpasswdGetSortEnum,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OcservUserOcservUsersSyncResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservUsersOcpasswdGet(
                authorization,
                page,
                size,
                order,
                sort,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['OcservOcpasswdApi.ocservUsersOcpasswdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {string} authorization Bearer TOKEN
         * @param {OcservUserSyncOcpasswdRequest} request list of users with config to sync in db
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservUsersOcpasswdSyncPost(
            authorization: string,
            request: OcservUserSyncOcpasswdRequest,
            options?: RawAxiosRequestConfig
        ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservUsersOcpasswdSyncPost(
                authorization,
                request,
                options
            );
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath =
                operationServerMap['OcservOcpasswdApi.ocservUsersOcpasswdSyncPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) =>
                createRequestFunction(
                    localVarAxiosArgs,
                    globalAxios,
                    BASE_PATH,
                    configuration
                )(axios, localVarOperationServerBasePath || basePath);
        }
    };
};

/**
 * OcservOcpasswdApi - factory interface
 * @export
 */
export const OcservOcpasswdApiFactory = function (
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance
) {
    const localVarFp = OcservOcpasswdApiFp(configuration);
    return {
        /**
         * Ocserv Users from ocpasswd file
         * @summary Ocserv Users from ocpasswd file
         * @param {OcservOcpasswdApiOcservUsersOcpasswdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdGet(
            requestParameters: OcservOcpasswdApiOcservUsersOcpasswdGetRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<OcservUserOcservUsersSyncResponse> {
            return localVarFp
                .ocservUsersOcpasswdGet(
                    requestParameters.authorization,
                    requestParameters.page,
                    requestParameters.size,
                    requestParameters.order,
                    requestParameters.sort,
                    options
                )
                .then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Users from ocpasswd file to db
         * @summary Ocserv Users from ocpasswd file to db
         * @param {OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersOcpasswdSyncPost(
            requestParameters: OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest,
            options?: RawAxiosRequestConfig
        ): AxiosPromise<Array<string>> {
            return localVarFp
                .ocservUsersOcpasswdSyncPost(requestParameters.authorization, requestParameters.request, options)
                .then((request) => request(axios, basePath));
        }
    };
};

/**
 * Request parameters for ocservUsersOcpasswdGet operation in OcservOcpasswdApi.
 * @export
 * @interface OcservOcpasswdApiOcservUsersOcpasswdGetRequest
 */
export interface OcservOcpasswdApiOcservUsersOcpasswdGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdGet
     */
    readonly authorization: string;

    /**
     * Page number, starting from 1
     * @type {number}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdGet
     */
    readonly page?: number;

    /**
     * Number of items per page
     * @type {number}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdGet
     */
    readonly size?: number;

    /**
     * Field to order by
     * @type {string}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdGet
     */
    readonly order?: string;

    /**
     * Sort order, either ASC or DESC
     * @type {'ASC' | 'DESC'}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdGet
     */
    readonly sort?: OcservUsersOcpasswdGetSortEnum;
}

/**
 * Request parameters for ocservUsersOcpasswdSyncPost operation in OcservOcpasswdApi.
 * @export
 * @interface OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest
 */
export interface OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdSyncPost
     */
    readonly authorization: string;

    /**
     * list of users with config to sync in db
     * @type {OcservUserSyncOcpasswdRequest}
     * @memberof OcservOcpasswdApiOcservUsersOcpasswdSyncPost
     */
    readonly request: OcservUserSyncOcpasswdRequest;
}

/**
 * OcservOcpasswdApi - object-oriented interface
 * @export
 * @class OcservOcpasswdApi
 * @extends {BaseAPI}
 */
export class OcservOcpasswdApi extends BaseAPI {
    /**
     * Ocserv Users from ocpasswd file
     * @summary Ocserv Users from ocpasswd file
     * @param {OcservOcpasswdApiOcservUsersOcpasswdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservOcpasswdApi
     */
    public ocservUsersOcpasswdGet(
        requestParameters: OcservOcpasswdApiOcservUsersOcpasswdGetRequest,
        options?: RawAxiosRequestConfig
    ) {
        return OcservOcpasswdApiFp(this.configuration)
            .ocservUsersOcpasswdGet(
                requestParameters.authorization,
                requestParameters.page,
                requestParameters.size,
                requestParameters.order,
                requestParameters.sort,
                options
            )
            .then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Users from ocpasswd file to db
     * @summary Ocserv Users from ocpasswd file to db
     * @param {OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservOcpasswdApi
     */
    public ocservUsersOcpasswdSyncPost(
        requestParameters: OcservOcpasswdApiOcservUsersOcpasswdSyncPostRequest,
        options?: RawAxiosRequestConfig
    ) {
        return OcservOcpasswdApiFp(this.configuration)
            .ocservUsersOcpasswdSyncPost(requestParameters.authorization, requestParameters.request, options)
            .then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const OcservUsersOcpasswdGetSortEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type OcservUsersOcpasswdGetSortEnum =
    (typeof OcservUsersOcpasswdGetSortEnum)[keyof typeof OcservUsersOcpasswdGetSortEnum];
