/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RepositoryTotalBandwidths } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * OcservBandwidthApi - axios parameter creator
 * @export
 */
export const OcservBandwidthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersTotalBandwidthGet: async (authorization: string, dateStart: string, dateEnd: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('ocservUsersTotalBandwidthGet', 'authorization', authorization)
            // verify required parameter 'dateStart' is not null or undefined
            assertParamExists('ocservUsersTotalBandwidthGet', 'dateStart', dateStart)
            // verify required parameter 'dateEnd' is not null or undefined
            assertParamExists('ocservUsersTotalBandwidthGet', 'dateEnd', dateEnd)
            const localVarPath = `/ocserv/users/total-bandwidth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (dateStart !== undefined) {
                localVarQueryParameter['date_start'] = dateStart;
            }

            if (dateEnd !== undefined) {
                localVarQueryParameter['date_end'] = dateEnd;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OcservBandwidthApi - functional programming interface
 * @export
 */
export const OcservBandwidthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OcservBandwidthApiAxiosParamCreator(configuration)
    return {
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ocservUsersTotalBandwidthGet(authorization: string, dateStart: string, dateEnd: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RepositoryTotalBandwidths>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ocservUsersTotalBandwidthGet(authorization, dateStart, dateEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OcservBandwidthApi.ocservUsersTotalBandwidthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OcservBandwidthApi - factory interface
 * @export
 */
export const OcservBandwidthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OcservBandwidthApiFp(configuration)
    return {
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {OcservBandwidthApiOcservUsersTotalBandwidthGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ocservUsersTotalBandwidthGet(requestParameters: OcservBandwidthApiOcservUsersTotalBandwidthGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<RepositoryTotalBandwidths> {
            return localVarFp.ocservUsersTotalBandwidthGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for ocservUsersTotalBandwidthGet operation in OcservBandwidthApi.
 * @export
 * @interface OcservBandwidthApiOcservUsersTotalBandwidthGetRequest
 */
export interface OcservBandwidthApiOcservUsersTotalBandwidthGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof OcservBandwidthApiOcservUsersTotalBandwidthGet
     */
    readonly authorization: string

    /**
     * date_start
     * @type {string}
     * @memberof OcservBandwidthApiOcservUsersTotalBandwidthGet
     */
    readonly dateStart: string

    /**
     * date_end
     * @type {string}
     * @memberof OcservBandwidthApiOcservUsersTotalBandwidthGet
     */
    readonly dateEnd: string
}

/**
 * OcservBandwidthApi - object-oriented interface
 * @export
 * @class OcservBandwidthApi
 * @extends {BaseAPI}
 */
export class OcservBandwidthApi extends BaseAPI {
    /**
     * Ocserv Users TotalBandwidth calculating
     * @summary Ocserv Users TotalBandwidth calculating
     * @param {OcservBandwidthApiOcservUsersTotalBandwidthGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OcservBandwidthApi
     */
    public ocservUsersTotalBandwidthGet(requestParameters: OcservBandwidthApiOcservUsersTotalBandwidthGetRequest, options?: RawAxiosRequestConfig) {
        return OcservBandwidthApiFp(this.configuration).ocservUsersTotalBandwidthGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(this.axios, this.basePath));
    }
}

