/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { ModelsDailyTraffic } from '../models';
// @ts-ignore
import type { ReportOcservUserReportResponse } from '../models';
// @ts-ignore
import type { ReportSessionLogsResponse } from '../models';
// @ts-ignore
import type { RepositoryTotalBandwidths } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * ReportApi - axios parameter creator
 * @export
 */
export const ReportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Ocserv session logs
         * @summary Ocserv session logs
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {ReportsSessionLogsGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {string} [dateStart] date_start
         * @param {string} [dateEnd] date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsSessionLogsGet: async (authorization: string, page?: number, size?: number, order?: string, sort?: ReportsSessionLogsGetSortEnum, dateStart?: string, dateEnd?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('reportsSessionLogsGet', 'authorization', authorization)
            const localVarPath = `/reports/session_logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (dateStart !== undefined) {
                localVarQueryParameter['date_start'] = dateStart;
            }

            if (dateEnd !== undefined) {
                localVarQueryParameter['date_end'] = dateEnd;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv Users Statistics
         * @summary Ocserv Users Statistics
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsStatisticsGet: async (authorization: string, dateStart: string, dateEnd: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('reportsStatisticsGet', 'authorization', authorization)
            // verify required parameter 'dateStart' is not null or undefined
            assertParamExists('reportsStatisticsGet', 'dateStart', dateStart)
            // verify required parameter 'dateEnd' is not null or undefined
            assertParamExists('reportsStatisticsGet', 'dateEnd', dateEnd)
            const localVarPath = `/reports/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (dateStart !== undefined) {
                localVarQueryParameter['date_start'] = dateStart;
            }

            if (dateEnd !== undefined) {
                localVarQueryParameter['date_end'] = dateEnd;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsTotalBandwidthGet: async (authorization: string, dateStart: string, dateEnd: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('reportsTotalBandwidthGet', 'authorization', authorization)
            // verify required parameter 'dateStart' is not null or undefined
            assertParamExists('reportsTotalBandwidthGet', 'dateStart', dateStart)
            // verify required parameter 'dateEnd' is not null or undefined
            assertParamExists('reportsTotalBandwidthGet', 'dateEnd', dateEnd)
            const localVarPath = `/reports/total-bandwidth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (dateStart !== undefined) {
                localVarQueryParameter['date_start'] = dateStart;
            }

            if (dateEnd !== undefined) {
                localVarQueryParameter['date_end'] = dateEnd;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Result of all user reports
         * @summary Result of all user reports
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsUsersGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('reportsUsersGet', 'authorization', authorization)
            const localVarPath = `/reports/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReportApi - functional programming interface
 * @export
 */
export const ReportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReportApiAxiosParamCreator(configuration)
    return {
        /**
         * Ocserv session logs
         * @summary Ocserv session logs
         * @param {string} authorization Bearer TOKEN
         * @param {number} [page] Page number, starting from 1
         * @param {number} [size] Number of items per page
         * @param {string} [order] Field to order by
         * @param {ReportsSessionLogsGetSortEnum} [sort] Sort order, either ASC or DESC
         * @param {string} [dateStart] date_start
         * @param {string} [dateEnd] date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportsSessionLogsGet(authorization: string, page?: number, size?: number, order?: string, sort?: ReportsSessionLogsGetSortEnum, dateStart?: string, dateEnd?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportSessionLogsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportsSessionLogsGet(authorization, page, size, order, sort, dateStart, dateEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportApi.reportsSessionLogsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Users Statistics
         * @summary Ocserv Users Statistics
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportsStatisticsGet(authorization: string, dateStart: string, dateEnd: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsDailyTraffic>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportsStatisticsGet(authorization, dateStart, dateEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportApi.reportsStatisticsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {string} authorization Bearer TOKEN
         * @param {string} dateStart date_start
         * @param {string} dateEnd date_end
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportsTotalBandwidthGet(authorization: string, dateStart: string, dateEnd: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RepositoryTotalBandwidths>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportsTotalBandwidthGet(authorization, dateStart, dateEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportApi.reportsTotalBandwidthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Result of all user reports
         * @summary Result of all user reports
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportsUsersGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReportOcservUserReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportsUsersGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportApi.reportsUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReportApi - factory interface
 * @export
 */
export const ReportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReportApiFp(configuration)
    return {
        /**
         * Ocserv session logs
         * @summary Ocserv session logs
         * @param {ReportApiReportsSessionLogsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsSessionLogsGet(requestParameters: ReportApiReportsSessionLogsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportSessionLogsResponse> {
            return localVarFp.reportsSessionLogsGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Users Statistics
         * @summary Ocserv Users Statistics
         * @param {ReportApiReportsStatisticsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsStatisticsGet(requestParameters: ReportApiReportsStatisticsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsDailyTraffic>> {
            return localVarFp.reportsStatisticsGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv Users TotalBandwidth calculating
         * @summary Ocserv Users TotalBandwidth calculating
         * @param {ReportApiReportsTotalBandwidthGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsTotalBandwidthGet(requestParameters: ReportApiReportsTotalBandwidthGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<RepositoryTotalBandwidths> {
            return localVarFp.reportsTotalBandwidthGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(axios, basePath));
        },
        /**
         * Result of all user reports
         * @summary Result of all user reports
         * @param {ReportApiReportsUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsUsersGet(requestParameters: ReportApiReportsUsersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReportOcservUserReportResponse> {
            return localVarFp.reportsUsersGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for reportsSessionLogsGet operation in ReportApi.
 * @export
 * @interface ReportApiReportsSessionLogsGetRequest
 */
export interface ReportApiReportsSessionLogsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly authorization: string

    /**
     * Page number, starting from 1
     * @type {number}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly page?: number

    /**
     * Number of items per page
     * @type {number}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly size?: number

    /**
     * Field to order by
     * @type {string}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly order?: string

    /**
     * Sort order, either ASC or DESC
     * @type {'ASC' | 'DESC'}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly sort?: ReportsSessionLogsGetSortEnum

    /**
     * date_start
     * @type {string}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly dateStart?: string

    /**
     * date_end
     * @type {string}
     * @memberof ReportApiReportsSessionLogsGet
     */
    readonly dateEnd?: string
}

/**
 * Request parameters for reportsStatisticsGet operation in ReportApi.
 * @export
 * @interface ReportApiReportsStatisticsGetRequest
 */
export interface ReportApiReportsStatisticsGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof ReportApiReportsStatisticsGet
     */
    readonly authorization: string

    /**
     * date_start
     * @type {string}
     * @memberof ReportApiReportsStatisticsGet
     */
    readonly dateStart: string

    /**
     * date_end
     * @type {string}
     * @memberof ReportApiReportsStatisticsGet
     */
    readonly dateEnd: string
}

/**
 * Request parameters for reportsTotalBandwidthGet operation in ReportApi.
 * @export
 * @interface ReportApiReportsTotalBandwidthGetRequest
 */
export interface ReportApiReportsTotalBandwidthGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof ReportApiReportsTotalBandwidthGet
     */
    readonly authorization: string

    /**
     * date_start
     * @type {string}
     * @memberof ReportApiReportsTotalBandwidthGet
     */
    readonly dateStart: string

    /**
     * date_end
     * @type {string}
     * @memberof ReportApiReportsTotalBandwidthGet
     */
    readonly dateEnd: string
}

/**
 * Request parameters for reportsUsersGet operation in ReportApi.
 * @export
 * @interface ReportApiReportsUsersGetRequest
 */
export interface ReportApiReportsUsersGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof ReportApiReportsUsersGet
     */
    readonly authorization: string
}

/**
 * ReportApi - object-oriented interface
 * @export
 * @class ReportApi
 * @extends {BaseAPI}
 */
export class ReportApi extends BaseAPI {
    /**
     * Ocserv session logs
     * @summary Ocserv session logs
     * @param {ReportApiReportsSessionLogsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public reportsSessionLogsGet(requestParameters: ReportApiReportsSessionLogsGetRequest, options?: RawAxiosRequestConfig) {
        return ReportApiFp(this.configuration).reportsSessionLogsGet(requestParameters.authorization, requestParameters.page, requestParameters.size, requestParameters.order, requestParameters.sort, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Users Statistics
     * @summary Ocserv Users Statistics
     * @param {ReportApiReportsStatisticsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public reportsStatisticsGet(requestParameters: ReportApiReportsStatisticsGetRequest, options?: RawAxiosRequestConfig) {
        return ReportApiFp(this.configuration).reportsStatisticsGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv Users TotalBandwidth calculating
     * @summary Ocserv Users TotalBandwidth calculating
     * @param {ReportApiReportsTotalBandwidthGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public reportsTotalBandwidthGet(requestParameters: ReportApiReportsTotalBandwidthGetRequest, options?: RawAxiosRequestConfig) {
        return ReportApiFp(this.configuration).reportsTotalBandwidthGet(requestParameters.authorization, requestParameters.dateStart, requestParameters.dateEnd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Result of all user reports
     * @summary Result of all user reports
     * @param {ReportApiReportsUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportApi
     */
    public reportsUsersGet(requestParameters: ReportApiReportsUsersGetRequest, options?: RawAxiosRequestConfig) {
        return ReportApiFp(this.configuration).reportsUsersGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ReportsSessionLogsGetSortEnum = {
    ASC: 'ASC',
    DESC: 'DESC'
} as const;
export type ReportsSessionLogsGetSortEnum = typeof ReportsSessionLogsGetSortEnum[keyof typeof ReportsSessionLogsGetSortEnum];
