/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MiddlewaresTooManyRequests } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
// @ts-ignore
import type { SystemdActionResponse } from '../models';
// @ts-ignore
import type { SystemdOcservSystemdStatus } from '../models';
/**
 * SystemdApi - axios parameter creator
 * @export
 */
export const SystemdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Disable ocserv systemd service (remove from auto start)
         * @summary Disable ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdDisablePost: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('systemdDisablePost', 'authorization', authorization)
            const localVarPath = `/systemd/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable ocserv systemd service (auto start on boot)
         * @summary Enable ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdEnablePost: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('systemdEnablePost', 'authorization', authorization)
            const localVarPath = `/systemd/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restart ocserv systemd service
         * @summary Restart ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdRestartPost: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('systemdRestartPost', 'authorization', authorization)
            const localVarPath = `/systemd/restart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Ocserv systemctl status
         * @summary Ocserv systemctl status
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdStatusGet: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('systemdStatusGet', 'authorization', authorization)
            const localVarPath = `/systemd/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemdApi - functional programming interface
 * @export
 */
export const SystemdApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemdApiAxiosParamCreator(configuration)
    return {
        /**
         * Disable ocserv systemd service (remove from auto start)
         * @summary Disable ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemdDisablePost(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemdActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemdDisablePost(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemdApi.systemdDisablePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable ocserv systemd service (auto start on boot)
         * @summary Enable ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemdEnablePost(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemdActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemdEnablePost(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemdApi.systemdEnablePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Restart ocserv systemd service
         * @summary Restart ocserv service
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemdRestartPost(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemdActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemdRestartPost(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemdApi.systemdRestartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Ocserv systemctl status
         * @summary Ocserv systemctl status
         * @param {string} authorization Bearer TOKEN
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async systemdStatusGet(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemdOcservSystemdStatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.systemdStatusGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemdApi.systemdStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemdApi - factory interface
 * @export
 */
export const SystemdApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemdApiFp(configuration)
    return {
        /**
         * Disable ocserv systemd service (remove from auto start)
         * @summary Disable ocserv service
         * @param {SystemdApiSystemdDisablePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdDisablePost(requestParameters: SystemdApiSystemdDisablePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SystemdActionResponse> {
            return localVarFp.systemdDisablePost(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Enable ocserv systemd service (auto start on boot)
         * @summary Enable ocserv service
         * @param {SystemdApiSystemdEnablePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdEnablePost(requestParameters: SystemdApiSystemdEnablePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SystemdActionResponse> {
            return localVarFp.systemdEnablePost(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Restart ocserv systemd service
         * @summary Restart ocserv service
         * @param {SystemdApiSystemdRestartPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdRestartPost(requestParameters: SystemdApiSystemdRestartPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SystemdActionResponse> {
            return localVarFp.systemdRestartPost(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Ocserv systemctl status
         * @summary Ocserv systemctl status
         * @param {SystemdApiSystemdStatusGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        systemdStatusGet(requestParameters: SystemdApiSystemdStatusGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<SystemdOcservSystemdStatus> {
            return localVarFp.systemdStatusGet(requestParameters.authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for systemdDisablePost operation in SystemdApi.
 * @export
 * @interface SystemdApiSystemdDisablePostRequest
 */
export interface SystemdApiSystemdDisablePostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemdApiSystemdDisablePost
     */
    readonly authorization: string
}

/**
 * Request parameters for systemdEnablePost operation in SystemdApi.
 * @export
 * @interface SystemdApiSystemdEnablePostRequest
 */
export interface SystemdApiSystemdEnablePostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemdApiSystemdEnablePost
     */
    readonly authorization: string
}

/**
 * Request parameters for systemdRestartPost operation in SystemdApi.
 * @export
 * @interface SystemdApiSystemdRestartPostRequest
 */
export interface SystemdApiSystemdRestartPostRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemdApiSystemdRestartPost
     */
    readonly authorization: string
}

/**
 * Request parameters for systemdStatusGet operation in SystemdApi.
 * @export
 * @interface SystemdApiSystemdStatusGetRequest
 */
export interface SystemdApiSystemdStatusGetRequest {
    /**
     * Bearer TOKEN
     * @type {string}
     * @memberof SystemdApiSystemdStatusGet
     */
    readonly authorization: string
}

/**
 * SystemdApi - object-oriented interface
 * @export
 * @class SystemdApi
 * @extends {BaseAPI}
 */
export class SystemdApi extends BaseAPI {
    /**
     * Disable ocserv systemd service (remove from auto start)
     * @summary Disable ocserv service
     * @param {SystemdApiSystemdDisablePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemdApi
     */
    public systemdDisablePost(requestParameters: SystemdApiSystemdDisablePostRequest, options?: RawAxiosRequestConfig) {
        return SystemdApiFp(this.configuration).systemdDisablePost(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enable ocserv systemd service (auto start on boot)
     * @summary Enable ocserv service
     * @param {SystemdApiSystemdEnablePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemdApi
     */
    public systemdEnablePost(requestParameters: SystemdApiSystemdEnablePostRequest, options?: RawAxiosRequestConfig) {
        return SystemdApiFp(this.configuration).systemdEnablePost(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Restart ocserv systemd service
     * @summary Restart ocserv service
     * @param {SystemdApiSystemdRestartPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemdApi
     */
    public systemdRestartPost(requestParameters: SystemdApiSystemdRestartPostRequest, options?: RawAxiosRequestConfig) {
        return SystemdApiFp(this.configuration).systemdRestartPost(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Ocserv systemctl status
     * @summary Ocserv systemctl status
     * @param {SystemdApiSystemdStatusGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemdApi
     */
    public systemdStatusGet(requestParameters: SystemdApiSystemdStatusGetRequest, options?: RawAxiosRequestConfig) {
        return SystemdApiFp(this.configuration).systemdStatusGet(requestParameters.authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

