/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { HomeGetHomeUser } from './home-get-home-user';
// May contain unused imports in some cases
// @ts-ignore
import type { HomeServerStatusResponse } from './home-server-status-response';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsDailyTraffic } from './models-daily-traffic';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsIPBanPoints } from './models-ipban-points';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryTopBandwidthUsers } from './repository-top-bandwidth-users';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryTotalBandwidths } from './repository-total-bandwidths';

/**
 *
 * @export
 * @interface HomeGetHomeResponse
 */
export interface HomeGetHomeResponse {
    /**
     *
     * @type {Array<ModelsIPBanPoints>}
     * @memberof HomeGetHomeResponse
     */
    ip_bans?: Array<ModelsIPBanPoints>;
    /**
     *
     * @type {HomeServerStatusResponse}
     * @memberof HomeGetHomeResponse
     */
    server_status: HomeServerStatusResponse;
    /**
     *
     * @type {Array<ModelsDailyTraffic>}
     * @memberof HomeGetHomeResponse
     */
    statistics?: Array<ModelsDailyTraffic>;
    /**
     *
     * @type {RepositoryTopBandwidthUsers}
     * @memberof HomeGetHomeResponse
     */
    top_bandwidth_user?: RepositoryTopBandwidthUsers;
    /**
     *
     * @type {RepositoryTotalBandwidths}
     * @memberof HomeGetHomeResponse
     */
    total_bandwidth?: RepositoryTotalBandwidths;
    /**
     *
     * @type {HomeGetHomeUser}
     * @memberof HomeGetHomeResponse
     */
    users?: HomeGetHomeUser;
}
