/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsOcservUserSessionLog
 */
export interface ModelsOcservUserSessionLog {
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserSessionLog
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserSessionLog
     */
    'event': ModelsOcservUserSessionLogEventEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserSessionLog
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserSessionLog
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserSessionLog
     */
    'username': string;
}

export const ModelsOcservUserSessionLogEventEnum = {
    USER_AGENT: 'user-agent',
    HANDSHAKE: 'handshake',
    PERIODIC_STATS: 'periodic-stats',
    DISCONNECT: 'disconnect'
} as const;

export type ModelsOcservUserSessionLogEventEnum = typeof ModelsOcservUserSessionLogEventEnum[keyof typeof ModelsOcservUserSessionLogEventEnum];


