/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ModelsDailyTraffic } from './models-daily-traffic';
// May contain unused imports in some cases
// @ts-ignore
import type { RepositoryTotalBandwidths } from './repository-total-bandwidths';

/**
 *
 * @export
 * @interface OcservUserStatisticsResponse
 */
export interface OcservUserStatisticsResponse {
    /**
     *
     * @type {Array<ModelsDailyTraffic>}
     * @memberof OcservUserStatisticsResponse
     */
    statistics: Array<ModelsDailyTraffic>;
    /**
     *
     * @type {RepositoryTotalBandwidths}
     * @memberof OcservUserStatisticsResponse
     */
    total_bandwidths: RepositoryTotalBandwidths;
}
