/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUserConfig } from './models-ocserv-user-config';
// May contain unused imports in some cases
// @ts-ignore
import type { UserOcpasswd } from './user-ocpasswd';

/**
 * 
 * @export
 * @interface OcservUserSyncOcpasswdRequest
 */
export interface OcservUserSyncOcpasswdRequest {
    /**
     * 
     * @type {ModelsOcservUserConfig}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'config'?: ModelsOcservUserConfig;
    /**
     * 
     * @type {string}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'expire_at'?: string;
    /**
     * 10 GiB
     * @type {number}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'traffic_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'traffic_type'?: OcservUserSyncOcpasswdRequestTrafficTypeEnum;
    /**
     * 
     * @type {Array<UserOcpasswd>}
     * @memberof OcservUserSyncOcpasswdRequest
     */
    'users': Array<UserOcpasswd>;
}

export const OcservUserSyncOcpasswdRequestTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive'
} as const;

export type OcservUserSyncOcpasswdRequestTrafficTypeEnum = typeof OcservUserSyncOcpasswdRequestTrafficTypeEnum[keyof typeof OcservUserSyncOcpasswdRequestTrafficTypeEnum];


