/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReportOcservUserReportResponse
 */
export interface ReportOcservUserReportResponse {
    /**
     * 
     * @type {number}
     * @memberof ReportOcservUserReportResponse
     */
    'active'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportOcservUserReportResponse
     */
    'deactivated'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportOcservUserReportResponse
     */
    'locked'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportOcservUserReportResponse
     */
    'online'?: number;
}

