/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemdOcservSystemdStatus
 */
export interface SystemdOcservSystemdStatus {
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'active_state'?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemdOcservSystemdStatus
     */
    'cpu_usage_nsec'?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemdOcservSystemdStatus
     */
    'main_pid'?: number;
    /**
     * 
     * @type {number}
     * @memberof SystemdOcservSystemdStatus
     */
    'memory'?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'start_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'sub_state'?: string;
    /**
     * 
     * @type {number}
     * @memberof SystemdOcservSystemdStatus
     */
    'tasks'?: number;
    /**
     * 
     * @type {string}
     * @memberof SystemdOcservSystemdStatus
     */
    'unit_file_state'?: string;
}

